name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: Run coverage
        run: go list ./... | grep -v support/test | tr '\n' ',' | rev | cut -c2- | rev | { read allpackages; go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=$allpackages ./...; }
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
